name: Merge Strategy
on:
  pull_request:
    branches:
      - main
jobs:
  message-check:
    name: Block Merge Commits

    runs-on: ubuntu-latest

    steps:
      - name: Block Merge Commits
        uses: Morishiri/block-merge-commits-action@v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

